[package]
name = "mpp-server"
version = "0.1.0"
authors = ["JellyBrick <shlee1503@naver.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-tungstenite = "0.10.1"
log = "0.4"
pretty_env_logger = "0.4"
unicode-segmentation = "1.3.0"